server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_test?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml